### ISSUE TITLE
Update knative-operator module to the latest apiVersions

### ISSUE THREAD

**Issue by eshepelyuk** [kcl-lang/modules#114]
For example `PingSource` is already `sources.knative.dev/v1`
https://knative.dev/docs/eventing/sources/ping-source/#__tabbed_1_3

but in module it's still  `v1beta2`
https://github.com/kcl-lang/modules/blob/58b31e8716eb6d8b36bfa20c60d633a2eb88ca4c/knative-operator/v1beta2/sources_knative_dev_v1beta2_ping_source.k#L14

**Comment by Peefy** [comment]
Closed by https://github.com/kcl-lang/modules/pull/115
